GET https://api.github.com/search/code?q=react+repo:cuongphuong/memo_data
Authorization: Token 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
###

PUT https://api.github.com/repos/cuongphuong/memo_data/contents/Js/post1.json
Authorization: Token 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
Accept: application/vnd.github.v3+json

{
    "message": "mm: add post 1", 
    "content": "ewoJInRpdGxlIjogIkphdmFzY3JpcHQgYmFzaWMgc2FtcGxlIiwKCSJjb250ZW50IjogImltcG9ydCBSZWFjdCBmcm9tICdyZWFjdCc7XFxuaW1wb3J0IFJlYWN0RE9NIGZyb20gJ3JlYWN0LWRvbSc7XFxuaW1wb3J0ICcuL2luZGV4LmNzcyc7XFxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcCc7XFxuaW1wb3J0IHJlcG9ydFdlYlZpdGFscyBmcm9tICcuL3JlcG9ydFdlYlZpdGFscyc7XFxuXFxuUmVhY3RET00ucmVuZGVyKFxcbiAgPFJlYWN0LlN0cmljdE1vZGU+XFxuICAgIDxBcHAgLz5cXG4gIDwvUmVhY3QuU3RyaWN0TW9kZT4sXFxuICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgncm9vdCcpXFxuKTtcXG5cXG4vLyBJZiB5b3Ugd2FudCB0byBzdGFydCBtZWFzdXJpbmcgcGVyZm9ybWFuY2UgaW4geW91ciBhcHAsIHBhc3MgYSBmdW5jdGlvblxcbi8vIHRvIGxvZyByZXN1bHRzIChmb3IgZXhhbXBsZTogcmVwb3J0V2ViVml0YWxzKGNvbnNvbGUubG9nKSlcXG4vLyBvciBzZW5kIHRvIGFuIGFuYWx5dGljcyBlbmRwb2ludC4gTGVhcm4gbW9yZTogaHR0cHM6Ly9iaXQubHkvQ1JBLXZpdGFsc1xcbnJlcG9ydFdlYlZpdGFscygpO1xcbiIKCSJjYXRlZ29yeSI6ICJKYXZhc2NsaXB0Igp9"
}
###

GET https://api.github.com/repos/cuongphuong/memo_data/contents/Js/post1.json
Authorization: Token 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
Accept: application/vnd.github.v3+json
###

GET https://api.github.com/repos/cuongphuong/memo_data/git/trees/main
Authorization: Token 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

###
GET https://api.github.com/repos/cuongphuong/memo_data/contents
Authorization: Token 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
Accept: application/vnd.github.v3+json
###
GET https://api.github.com/repos/cuongphuong/memo_data/contents/ParentTest1/test1.md?ref=main
Authorization: Token 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
Accept: application/vnd.github.v3+json