GET https://api.github.com/repos/cuongphuong/memo_data/git/refs/heads/main/
Authorization: Token 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
Accept: application/vnd.github.v3+json
###

PUT https://api.github.com/repos/cuongphuong/memo_data/contents/folder1sfsdfsdfsdf/sddddddddd.md
Authorization: Token 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
Accept: application/vnd.github.v3+json

{
    "message": "mm: update", 
    "content": "LS0tCmlkOiAxNjM5NzMxNTQ0OTk3CnRpdGxlOiBzZGRkZGRkZGRkCmNhdGVnb3J5OiBmb2xkZXIxc2ZzZGZzZGZzZGYvCi0tLQoKfCBIZWFkIHwgSGVhZCB8IEhlYWQgfCBIZWFkIHwgSGVhZCB8IEhlYWQgfAp8IC0tLSB8IC0tLSB8IC0tLSB8IC0tLSB8IC0tLSB8IC0tLSB8CnwgRGF0YSB8IERhdGEgfCBEYXRhIHwgRGF0YSB8IERhdGEgfCBEYXRhIHwKfCBEYXRhIHwgRGF0YSB8IERhdGEgfCBEYXRhIHwgRGF0YSB8IERhdGEgfAp8IERhdGEgfCBEYXRhIHwgRGF0YSB8IERhdGEgfCBEYXRhIHwgRGF0YSB8CnwgRGF0YSB8IERhdGEgfCBEYXRhIHwgRGF0YSB8IERhdGEgfCBEYXRhIHw==",
    "sha": "002be32434240c6b451f92077035793279f5baf4"
}

###
GET https://api.github.com/repos/cuongphuong/memo_data/contents/folder1sfsdfsdfsdf/sddddddddd.md
Authorization: Token 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
Accept: application/vnd.github.v3+json


###
POST  https://api.github.com/markdown
Authorization: Token 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
Accept: application/vnd.github.v3+json

{
    "text":"```js\n import React from 'react'; \n```"
}


###
POST  https://api.github.com/repos/cuongphuong/memo_data/git/trees/53badffa9ab32fa8e1be9ee1bad61a3c3195f907
Authorization: Token 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
Accept: application/vnd.github.v3+json


###
GET https://api.github.com/repos/cuongphuong/memo_data/git/trees/76ba6ba67867c6069cbb9c377a0a2c909145c778
Authorization: Token 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
Accept: application/vnd.github.v3+json


###
GET https://api.github.com/users/buiducnam
Authorization: Token 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
Accept: application/vnd.github.v3+json


###

GET https://api.github.com/repos/cuongphuong/memo_data/contents/Js/post1.json
Authorization: Token *
Accept: application/vnd.github.v3+json
###

GET https://api.github.com/repos/cuongphuong/memo_data/git/trees/4e4a543a6dd8e33b4405e79c0f7c45834f1991da
Authorization: Token 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

###
GET https://api.github.com/repos/cuongphuong/memo_data/contents
Authorization: Token *
Accept: application/vnd.github.v3+json
###
GET https://api.github.com/repos/cuongphuong/memo_data/contents/ParentTest1/test1.md?ref=main
Authorization: Token *
Accept: application/vnd.github.v3+json

###

POST https://api.github.com/markdown
Accept: application/vnd.github.v3+json

{
    "text":"```js\n import React from 'react'; \n```"
}